version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "2000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - tax-frontend

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tax_assistant
    expose:
      - "8000"
    depends_on:
      - db

  tax-frontend:
    image: tax-frontend
    expose:
      - "5173"

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tax_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: