from types import UnionType

from pydantic import BaseModel, Field, constr, validator, ConfigDict
from typing import Optional, Any, Dict, Annotated, Literal, get_origin, get_args
from datetime import date
from enum import Enum
import re

from tax_assistant.models.gminy import Municipality, County, Voivodeship

from pydantic import BaseModel, field_validator, ValidationError


class ErrorSuppressingModel(BaseModel):
    @classmethod
    def model_validate(cls, obj):
        fields = {}
        for name, field in cls.model_fields.items():
            try:
                value = obj.get(name)
                if value is not None:
                    # Validate the field
                    fields[name] = field.validate(value, {}, loc=name)
                else:
                    fields[name] = None
            except ValidationError:
                # If validation fails, set the field to None
                fields[name] = None

        # Create and return the model instance
        return cls(**fields)

    @field_validator('*', mode='after')
    def validate_fields(cls, value, info):
        return value  # This validator is just to trigger the custom model_validate method


def form_field(form_field_number: str):
    def decorator(field: Field):
        field.json_schema_extra = {"form_field_number": form_field_number}
        return field

    return decorator


class CelZlozenia(Enum):
    ZLOZENIE = "ZLOZENIE"
    KOREKTA = "KOREKTA"


class TaxOffice(Enum):
    URZĄD_SKARBOWY_W_BOLESŁAWCU = "URZĄD_SKARBOWY_W_BOLESŁAWCU"
    URZĄD_SKARBOWY_W_BYSTRZYCY_KŁODZKIEJ = "URZĄD_SKARBOWY_W_BYSTRZYCY_KŁODZKIEJ"
    URZĄD_SKARBOWY_W_DZIERŻONIOWIE = "URZĄD_SKARBOWY_W_DZIERŻONIOWIE"
    URZĄD_SKARBOWY_W_GŁOGOWIE = "URZĄD_SKARBOWY_W_GŁOGOWIE"
    URZĄD_SKARBOWY_W_JAWORZE = "URZĄD_SKARBOWY_W_JAWORZE"
    URZĄD_SKARBOWY_W_JELENIEJ_GÓRZE = "URZĄD_SKARBOWY_W_JELENIEJ_GÓRZE"
    URZĄD_SKARBOWY_W_KAMIENNEJ_GÓRZE = "URZĄD_SKARBOWY_W_KAMIENNEJ_GÓRZE"
    URZĄD_SKARBOWY_W_KŁODZKU = "URZĄD_SKARBOWY_W_KŁODZKU"
    URZĄD_SKARBOWY_W_LEGNICY = "URZĄD_SKARBOWY_W_LEGNICY"
    URZĄD_SKARBOWY_W_LUBANIU = "URZĄD_SKARBOWY_W_LUBANIU"
    URZĄD_SKARBOWY_W_LUBINIE = "URZĄD_SKARBOWY_W_LUBINIE"
    URZĄD_SKARBOWY_W_LWÓWKU_ŚLĄSKIM = "URZĄD_SKARBOWY_W_LWÓWKU_ŚLĄSKIM"
    URZĄD_SKARBOWY_W_MILICZU = "URZĄD_SKARBOWY_W_MILICZU"
    URZĄD_SKARBOWY_W_NOWEJ_RUDZIE = "URZĄD_SKARBOWY_W_NOWEJ_RUDZIE"
    URZĄD_SKARBOWY_W_OLEŚNICY = "URZĄD_SKARBOWY_W_OLEŚNICY"
    URZĄD_SKARBOWY_W_OŁAWIE = "URZĄD_SKARBOWY_W_OŁAWIE"
    URZĄD_SKARBOWY_W_STRZELINIE = "URZĄD_SKARBOWY_W_STRZELINIE"
    URZĄD_SKARBOWY_W_ŚRODZIE_ŚLĄSKIEJ = "URZĄD_SKARBOWY_W_ŚRODZIE_ŚLĄSKIEJ"
    URZĄD_SKARBOWY_W_ŚWIDNICY = "URZĄD_SKARBOWY_W_ŚWIDNICY"
    URZĄD_SKARBOWY_W_TRZEBNICY = "URZĄD_SKARBOWY_W_TRZEBNICY"
    URZĄD_SKARBOWY_W_WAŁBRZYCHU = "URZĄD_SKARBOWY_W_WAŁBRZYCHU"
    URZĄD_SKARBOWY_W_WOŁOWIE = "URZĄD_SKARBOWY_W_WOŁOWIE"
    URZĄD_SKARBOWY_WROCŁAW_FABRYCZNA = "URZĄD_SKARBOWY_WROCŁAW_FABRYCZNA"
    URZĄD_SKARBOWY_WROCŁAW_KRZYKI = "URZĄD_SKARBOWY_WROCŁAW_KRZYKI"
    URZĄD_SKARBOWY_WROCŁAW_PSIE_POLE = "URZĄD_SKARBOWY_WROCŁAW_PSIE_POLE"
    URZĄD_SKARBOWY_WROCŁAW_STARE_MIASTO = "URZĄD_SKARBOWY_WROCŁAW_STARE_MIASTO"
    URZĄD_SKARBOWY_WROCŁAW_ŚRÓDMIEŚCIE = "URZĄD_SKARBOWY_WROCŁAW_ŚRÓDMIEŚCIE"
    PIERWSZY_URZĄD_SKARBOWY_WE_WROCŁAWIU = "PIERWSZY_URZĄD_SKARBOWY_WE_WROCŁAWIU"
    URZĄD_SKARBOWY_W_ZĄBKOWICACH_ŚLĄSKICH = "URZĄD_SKARBOWY_W_ZĄBKOWICACH_ŚLĄSKICH"
    URZĄD_SKARBOWY_W_ZGORZELCU = "URZĄD_SKARBOWY_W_ZGORZELCU"
    URZĄD_SKARBOWY_W_ZŁOTORYI = "URZĄD_SKARBOWY_W_ZŁOTORYI"
    URZĄD_SKARBOWY_W_GÓRZE = "URZĄD_SKARBOWY_W_GÓRZE"
    URZĄD_SKARBOWY_W_POLKOWICACH = "URZĄD_SKARBOWY_W_POLKOWICACH"
    DOLNOŚLĄSKI_URZĄD_SKARBOWY_WE_WROCŁAWIU = "DOLNOŚLĄSKI_URZĄD_SKARBOWY_WE_WROCŁAWIU"
    URZĄD_SKARBOWY_W_ALEKSANDROWIE_KUJAWSKIM = "URZĄD_SKARBOWY_W_ALEKSANDROWIE_KUJAWSKIM"
    URZĄD_SKARBOWY_W_BRODNICY = "URZĄD_SKARBOWY_W_BRODNICY"
    PIERWSZY_URZĄD_SKARBOWY_W_BYDGOSZCZY = "PIERWSZY_URZĄD_SKARBOWY_W_BYDGOSZCZY"
    DRUGI_URZĄD_SKARBOWY_W_BYDGOSZCZY = "DRUGI_URZĄD_SKARBOWY_W_BYDGOSZCZY"
    TRZECI_URZĄD_SKARBOWY_W_BYDGOSZCZY = "TRZECI_URZĄD_SKARBOWY_W_BYDGOSZCZY"
    URZĄD_SKARBOWY_W_CHEŁMNIE = "URZĄD_SKARBOWY_W_CHEŁMNIE"
    URZĄD_SKARBOWY_W_GRUDZIĄDZU = "URZĄD_SKARBOWY_W_GRUDZIĄDZU"
    URZĄD_SKARBOWY_W_INOWROCŁAWIU = "URZĄD_SKARBOWY_W_INOWROCŁAWIU"
    URZĄD_SKARBOWY_W_LIPNIE = "URZĄD_SKARBOWY_W_LIPNIE"
    URZĄD_SKARBOWY_W_MOGILNIE = "URZĄD_SKARBOWY_W_MOGILNIE"
    URZĄD_SKARBOWY_W_NAKLE_NAD_NOTECIĄ = "URZĄD_SKARBOWY_W_NAKLE_NAD_NOTECIĄ"
    URZĄD_SKARBOWY_W_RADZIEJOWIE = "URZĄD_SKARBOWY_W_RADZIEJOWIE"
    URZĄD_SKARBOWY_W_RYPINIE = "URZĄD_SKARBOWY_W_RYPINIE"
    URZĄD_SKARBOWY_W_ŚWIECIU = "URZĄD_SKARBOWY_W_ŚWIECIU"
    PIERWSZY_URZĄD_SKARBOWY_W_TORUNIU = "PIERWSZY_URZĄD_SKARBOWY_W_TORUNIU"
    DRUGI_URZĄD_SKARBOWY_W_TORUNIU = "DRUGI_URZĄD_SKARBOWY_W_TORUNIU"
    URZĄD_SKARBOWY_W_TUCHOLI = "URZĄD_SKARBOWY_W_TUCHOLI"
    URZĄD_SKARBOWY_W_WĄBRZEŹNIE = "URZĄD_SKARBOWY_W_WĄBRZEŹNIE"
    URZĄD_SKARBOWY_WE_WŁOCŁAWKU = "URZĄD_SKARBOWY_WE_WŁOCŁAWKU"
    URZĄD_SKARBOWY_W_ŻNINIE = "URZĄD_SKARBOWY_W_ŻNINIE"
    URZĄD_SKARBOWY_W_GOLUBIU_DOBRZYNIU = "URZĄD_SKARBOWY_W_GOLUBIU_DOBRZYNIU"
    URZĄD_SKARBOWY_W_SĘPÓLNIE_KRAJEŃSKIM = "URZĄD_SKARBOWY_W_SĘPÓLNIE_KRAJEŃSKIM"
    KUJAWSKO_POMORSKI_URZĄD_SKARBOWY_W_BYDGOSZCZY = "KUJAWSKO_POMORSKI_URZĄD_SKARBOWY_W_BYDGOSZCZY"
    URZĄD_SKARBOWY_W_BIAŁEJ_PODLASKIEJ = "URZĄD_SKARBOWY_W_BIAŁEJ_PODLASKIEJ"
    URZĄD_SKARBOWY_W_BIŁGORAJU = "URZĄD_SKARBOWY_W_BIŁGORAJU"
    URZĄD_SKARBOWY_W_CHEŁMIE = "URZĄD_SKARBOWY_W_CHEŁMIE"
    URZĄD_SKARBOWY_W_HRUBIESZOWIE = "URZĄD_SKARBOWY_W_HRUBIESZOWIE"
    URZĄD_SKARBOWY_W_JANOWIE_LUBELSKIM = "URZĄD_SKARBOWY_W_JANOWIE_LUBELSKIM"
    URZĄD_SKARBOWY_W_KRASNYMSTAWIE = "URZĄD_SKARBOWY_W_KRASNYMSTAWIE"
    URZĄD_SKARBOWY_W_KRAŚNIKU = "URZĄD_SKARBOWY_W_KRAŚNIKU"
    URZĄD_SKARBOWY_W_LUBARTOWIE = "URZĄD_SKARBOWY_W_LUBARTOWIE"
    PIERWSZY_URZĄD_SKARBOWY_W_LUBLINIE = "PIERWSZY_URZĄD_SKARBOWY_W_LUBLINIE"
    DRUGI_URZĄD_SKARBOWY_W_LUBLINIE = "DRUGI_URZĄD_SKARBOWY_W_LUBLINIE"
    TRZECI_URZĄD_SKARBOWY_W_LUBLINIE = "TRZECI_URZĄD_SKARBOWY_W_LUBLINIE"
    URZĄD_SKARBOWY_W_ŁUKOWIE = "URZĄD_SKARBOWY_W_ŁUKOWIE"
    URZĄD_SKARBOWY_W_OPOLU_LUBELSKIM = "URZĄD_SKARBOWY_W_OPOLU_LUBELSKIM"
    URZĄD_SKARBOWY_W_PARCZEWIE = "URZĄD_SKARBOWY_W_PARCZEWIE"
    URZĄD_SKARBOWY_W_PUŁAWACH = "URZĄD_SKARBOWY_W_PUŁAWACH"
    URZĄD_SKARBOWY_W_RADZYNIU_PODLASKIM = "URZĄD_SKARBOWY_W_RADZYNIU_PODLASKIM"
    URZĄD_SKARBOWY_W_TOMASZOWIE_LUBELSKIM = "URZĄD_SKARBOWY_W_TOMASZOWIE_LUBELSKIM"
    URZĄD_SKARBOWY_WE_WŁODAWIE = "URZĄD_SKARBOWY_WE_WŁODAWIE"
    URZĄD_SKARBOWY_W_ZAMOŚCIU = "URZĄD_SKARBOWY_W_ZAMOŚCIU"
    URZĄD_SKARBOWY_W_ŁĘCZNEJ = "URZĄD_SKARBOWY_W_ŁĘCZNEJ"
    URZĄD_SKARBOWY_W_RYKACH = "URZĄD_SKARBOWY_W_RYKACH"
    LUBELSKI_URZĄD_SKARBOWY_W_LUBLINIE = "LUBELSKI_URZĄD_SKARBOWY_W_LUBLINIE"
    URZĄD_SKARBOWY_W_GORZOWIE_WIELKOPOLSKIM = "URZĄD_SKARBOWY_W_GORZOWIE_WIELKOPOLSKIM"
    URZĄD_SKARBOWY_W_KROŚNIE_ODRZAŃSKIM = "URZĄD_SKARBOWY_W_KROŚNIE_ODRZAŃSKIM"
    URZĄD_SKARBOWY_W_MIĘDZYRZECZU = "URZĄD_SKARBOWY_W_MIĘDZYRZECZU"
    URZĄD_SKARBOWY_W_NOWEJ_SOLI = "URZĄD_SKARBOWY_W_NOWEJ_SOLI"
    URZĄD_SKARBOWY_W_SŁUBICACH = "URZĄD_SKARBOWY_W_SŁUBICACH"
    URZĄD_SKARBOWY_W_ŚWIEBODZINIE = "URZĄD_SKARBOWY_W_ŚWIEBODZINIE"
    PIERWSZY_URZĄD_SKARBOWY_W_ZIELONEJ_GÓRZE = "PIERWSZY_URZĄD_SKARBOWY_W_ZIELONEJ_GÓRZE"
    DRUGI_URZĄD_SKARBOWY_W_ZIELONEJ_GÓRZE = "DRUGI_URZĄD_SKARBOWY_W_ZIELONEJ_GÓRZE"
    URZĄD_SKARBOWY_W_ŻAGANIU = "URZĄD_SKARBOWY_W_ŻAGANIU"
    URZĄD_SKARBOWY_W_ŻARACH = "URZĄD_SKARBOWY_W_ŻARACH"
    URZĄD_SKARBOWY_W_DREZDENKU = "URZĄD_SKARBOWY_W_DREZDENKU"
    URZĄD_SKARBOWY_W_SULĘCINIE = "URZĄD_SKARBOWY_W_SULĘCINIE"
    URZĄD_SKARBOWY_WE_WSCHOWIE = "URZĄD_SKARBOWY_WE_WSCHOWIE"
    LUBUSKI_URZĄD_SKARBOWY_W_ZIELONEJ_GÓRZE = "LUBUSKI_URZĄD_SKARBOWY_W_ZIELONEJ_GÓRZE"
    URZĄD_SKARBOWY_W_BEŁCHATOWIE = "URZĄD_SKARBOWY_W_BEŁCHATOWIE"
    URZĄD_SKARBOWY_W_BRZEZINACH = "URZĄD_SKARBOWY_W_BRZEZINACH"
    URZĄD_SKARBOWY_W_GŁOWNIE = "URZĄD_SKARBOWY_W_GŁOWNIE"
    URZĄD_SKARBOWY_W_KUTNIE = "URZĄD_SKARBOWY_W_KUTNIE"
    URZĄD_SKARBOWY_W_ŁASKU = "URZĄD_SKARBOWY_W_ŁASKU"
    URZĄD_SKARBOWY_W_ŁOWICZU = "URZĄD_SKARBOWY_W_ŁOWICZU"
    PIERWSZY_URZĄD_SKARBOWY_ŁÓDŹ_BAŁUTY = "PIERWSZY_URZĄD_SKARBOWY_ŁÓDŹ_BAŁUTY"
    DRUGI_URZĄD_SKARBOWY_ŁÓDŹ_BAŁUTY = "DRUGI_URZĄD_SKARBOWY_ŁÓDŹ_BAŁUTY"
    PIERWSZY_URZĄD_SKARBOWY_ŁÓDŹ_GÓRNA = "PIERWSZY_URZĄD_SKARBOWY_ŁÓDŹ_GÓRNA"
    DRUGI_URZĄD_SKARBOWY_ŁÓDŹ_GÓRNA = "DRUGI_URZĄD_SKARBOWY_ŁÓDŹ_GÓRNA"
    URZĄD_SKARBOWY_ŁÓDŹ_POLESIE = "URZĄD_SKARBOWY_ŁÓDŹ_POLESIE"
    URZĄD_SKARBOWY_ŁÓDŹ_ŚRÓDMIEŚCIE = "URZĄD_SKARBOWY_ŁÓDŹ_ŚRÓDMIEŚCIE"
    URZĄD_SKARBOWY_ŁÓDŹ_WIDZEW = "URZĄD_SKARBOWY_ŁÓDŹ_WIDZEW"
    URZĄD_SKARBOWY_W_OPOCZNIE = "URZĄD_SKARBOWY_W_OPOCZNIE"
    URZĄD_SKARBOWY_W_PABIANICACH = "URZĄD_SKARBOWY_W_PABIANICACH"
    URZĄD_SKARBOWY_W_PIOTRKOWIE_TRYBUNALSKIM = "URZĄD_SKARBOWY_W_PIOTRKOWIE_TRYBUNALSKIM"
    URZĄD_SKARBOWY_W_PODDĘBICACH = "URZĄD_SKARBOWY_W_PODDĘBICACH"
    URZĄD_SKARBOWY_W_RADOMSKU = "URZĄD_SKARBOWY_W_RADOMSKU"
    URZĄD_SKARBOWY_W_RAWIE_MAZOWIECKIEJ = "URZĄD_SKARBOWY_W_RAWIE_MAZOWIECKIEJ"
    URZĄD_SKARBOWY_W_SIERADZU = "URZĄD_SKARBOWY_W_SIERADZU"
    URZĄD_SKARBOWY_W_SKIERNIEWICACH = "URZĄD_SKARBOWY_W_SKIERNIEWICACH"
    URZĄD_SKARBOWY_W_TOMASZOWIE_MAZOWIECKIM = "URZĄD_SKARBOWY_W_TOMASZOWIE_MAZOWIECKIM"
    URZĄD_SKARBOWY_W_WIELUNIU = "URZĄD_SKARBOWY_W_WIELUNIU"
    URZĄD_SKARBOWY_W_ZDUŃSKIEJ_WOLI = "URZĄD_SKARBOWY_W_ZDUŃSKIEJ_WOLI"
    URZĄD_SKARBOWY_W_ZGIERZU = "URZĄD_SKARBOWY_W_ZGIERZU"
    URZĄD_SKARBOWY_W_WIERUSZOWIE = "URZĄD_SKARBOWY_W_WIERUSZOWIE"
    URZĄD_SKARBOWY_W_ŁĘCZYCY = "URZĄD_SKARBOWY_W_ŁĘCZYCY"
    URZĄD_SKARBOWY_W_PAJĘCZNIE = "URZĄD_SKARBOWY_W_PAJĘCZNIE"
    ŁÓDZKI_URZĄD_SKARBOWY_W_ŁODZI = "ŁÓDZKI_URZĄD_SKARBOWY_W_ŁODZI"
    URZĄD_SKARBOWY_W_BOCHNI = "URZĄD_SKARBOWY_W_BOCHNI"
    URZĄD_SKARBOWY_W_BRZESKU = "URZĄD_SKARBOWY_W_BRZESKU"
    URZĄD_SKARBOWY_W_CHRZANOWIE = "URZĄD_SKARBOWY_W_CHRZANOWIE"
    URZĄD_SKARBOWY_W_DĄBROWIE_TARNOWSKIEJ = "URZĄD_SKARBOWY_W_DĄBROWIE_TARNOWSKIEJ"
    URZĄD_SKARBOWY_W_GORLICACH = "URZĄD_SKARBOWY_W_GORLICACH"
    PIERWSZY_URZĄD_SKARBOWY_KRAKÓW = "PIERWSZY_URZĄD_SKARBOWY_KRAKÓW"
    URZĄD_SKARBOWY_KRAKÓW_KROWODRZA = "URZĄD_SKARBOWY_KRAKÓW_KROWODRZA"
    URZĄD_SKARBOWY_KRAKÓW_NOWA_HUTA = "URZĄD_SKARBOWY_KRAKÓW_NOWA_HUTA"
    URZĄD_SKARBOWY_KRAKÓW_PODGÓRZE = "URZĄD_SKARBOWY_KRAKÓW_PODGÓRZE"
    URZĄD_SKARBOWY_KRAKÓW_PRĄDNIK = "URZĄD_SKARBOWY_KRAKÓW_PRĄDNIK"
    URZĄD_SKARBOWY_KRAKÓW_STARE_MIASTO = "URZĄD_SKARBOWY_KRAKÓW_STARE_MIASTO"
    URZĄD_SKARBOWY_KRAKÓW_ŚRÓDMIEŚCIE = "URZĄD_SKARBOWY_KRAKÓW_ŚRÓDMIEŚCIE"
    URZĄD_SKARBOWY_W_LIMANOWEJ = "URZĄD_SKARBOWY_W_LIMANOWEJ"
    URZĄD_SKARBOWY_W_MIECHOWIE = "URZĄD_SKARBOWY_W_MIECHOWIE"
    URZĄD_SKARBOWY_W_MYŚLENICACH = "URZĄD_SKARBOWY_W_MYŚLENICACH"
    URZĄD_SKARBOWY_W_NOWYM_SĄCZU = "URZĄD_SKARBOWY_W_NOWYM_SĄCZU"
    URZĄD_SKARBOWY_W_NOWYM_TARGU = "URZĄD_SKARBOWY_W_NOWYM_TARGU"
    URZĄD_SKARBOWY_W_OLKUSZU = "URZĄD_SKARBOWY_W_OLKUSZU"
    URZĄD_SKARBOWY_W_OŚWIĘCIMIU = "URZĄD_SKARBOWY_W_OŚWIĘCIMIU"
    URZĄD_SKARBOWY_W_PROSZOWICACH = "URZĄD_SKARBOWY_W_PROSZOWICACH"
    URZĄD_SKARBOWY_W_SUCHEJ_BESKIDZKIEJ = "URZĄD_SKARBOWY_W_SUCHEJ_BESKIDZKIEJ"
    PIERWSZY_URZĄD_SKARBOWY_W_TARNOWIE = "PIERWSZY_URZĄD_SKARBOWY_W_TARNOWIE"
    DRUGI_URZĄD_SKARBOWY_W_TARNOWIE = "DRUGI_URZĄD_SKARBOWY_W_TARNOWIE"
    URZĄD_SKARBOWY_W_WADOWICACH = "URZĄD_SKARBOWY_W_WADOWICACH"
    URZĄD_SKARBOWY_W_WIELICZCE = "URZĄD_SKARBOWY_W_WIELICZCE"
    URZĄD_SKARBOWY_W_ZAKOPANEM = "URZĄD_SKARBOWY_W_ZAKOPANEM"
    DRUGI_URZĄD_SKARBOWY_KRAKÓW = "DRUGI_URZĄD_SKARBOWY_KRAKÓW"
    MAŁOPOLSKI_URZĄD_SKARBOWY_W_KRAKOWIE = "MAŁOPOLSKI_URZĄD_SKARBOWY_W_KRAKOWIE"
    URZĄD_SKARBOWY_W_BIAŁOBRZEGACH = "URZĄD_SKARBOWY_W_BIAŁOBRZEGACH"
    URZĄD_SKARBOWY_W_CIECHANOWIE = "URZĄD_SKARBOWY_W_CIECHANOWIE"
    URZĄD_SKARBOWY_W_GARWOLINIE = "URZĄD_SKARBOWY_W_GARWOLINIE"
    URZĄD_SKARBOWY_W_GOSTYNINIE = "URZĄD_SKARBOWY_W_GOSTYNINIE"
    URZĄD_SKARBOWY_W_GRODZISKU_MAZOWIECKIM = "URZĄD_SKARBOWY_W_GRODZISKU_MAZOWIECKIM"
    URZĄD_SKARBOWY_W_GRÓJCU = "URZĄD_SKARBOWY_W_GRÓJCU"
    URZĄD_SKARBOWY_W_KOZIENICACH = "URZĄD_SKARBOWY_W_KOZIENICACH"
    URZĄD_SKARBOWY_W_LEGIONOWIE = "URZĄD_SKARBOWY_W_LEGIONOWIE"
    URZĄD_SKARBOWY_W_ŁOSICACH = "URZĄD_SKARBOWY_W_ŁOSICACH"
    URZĄD_SKARBOWY_W_MAKOWIE_MAZOWIECKIM = "URZĄD_SKARBOWY_W_MAKOWIE_MAZOWIECKIM"
    URZĄD_SKARBOWY_W_MIŃSKU_MAZOWIECKIM = "URZĄD_SKARBOWY_W_MIŃSKU_MAZOWIECKIM"
    URZĄD_SKARBOWY_W_MŁAWIE = "URZĄD_SKARBOWY_W_MŁAWIE"
    URZĄD_SKARBOWY_W_NOWYM_DWORZE_MAZOWIECKIM = "URZĄD_SKARBOWY_W_NOWYM_DWORZE_MAZOWIECKIM"
    URZĄD_SKARBOWY_W_OSTROŁĘCE = "URZĄD_SKARBOWY_W_OSTROŁĘCE"
    URZĄD_SKARBOWY_W_OSTROWI_MAZOWIECKIEJ = "URZĄD_SKARBOWY_W_OSTROWI_MAZOWIECKIEJ"
    URZĄD_SKARBOWY_W_OTWOCKU = "URZĄD_SKARBOWY_W_OTWOCKU"
    URZĄD_SKARBOWY_W_PIASECZNIE = "URZĄD_SKARBOWY_W_PIASECZNIE"
    URZĄD_SKARBOWY_W_PŁOCKU = "URZĄD_SKARBOWY_W_PŁOCKU"
    URZĄD_SKARBOWY_W_PŁOŃSKU = "URZĄD_SKARBOWY_W_PŁOŃSKU"
    URZĄD_SKARBOWY_W_PRUSZKOWIE = "URZĄD_SKARBOWY_W_PRUSZKOWIE"
    URZĄD_SKARBOWY_W_PRZASNYSZU = "URZĄD_SKARBOWY_W_PRZASNYSZU"
    URZĄD_SKARBOWY_W_PUŁTUSKU = "URZĄD_SKARBOWY_W_PUŁTUSKU"
    PIERWSZY_URZĄD_SKARBOWY_W_RADOMIU = "PIERWSZY_URZĄD_SKARBOWY_W_RADOMIU"
    DRUGI_URZĄD_SKARBOWY_W_RADOMIU = "DRUGI_URZĄD_SKARBOWY_W_RADOMIU"
    URZĄD_SKARBOWY_W_SIEDLCACH = "URZĄD_SKARBOWY_W_SIEDLCACH"
    URZĄD_SKARBOWY_W_SIERPCU = "URZĄD_SKARBOWY_W_SIERPCU"
    URZĄD_SKARBOWY_W_SOCHACZEWIE = "URZĄD_SKARBOWY_W_SOCHACZEWIE"
    URZĄD_SKARBOWY_W_SOKOŁOWIE_PODLASKIM = "URZĄD_SKARBOWY_W_SOKOŁOWIE_PODLASKIM"
    URZĄD_SKARBOWY_W_SZYDŁOWCU = "URZĄD_SKARBOWY_W_SZYDŁOWCU"
    URZĄD_SKARBOWY_WARSZAWA_BEMOWO = "URZĄD_SKARBOWY_WARSZAWA_BEMOWO"
    URZĄD_SKARBOWY_WARSZAWA_BIELANY = "URZĄD_SKARBOWY_WARSZAWA_BIELANY"
    URZĄD_SKARBOWY_WARSZAWA_MOKOTÓW = "URZĄD_SKARBOWY_WARSZAWA_MOKOTÓW"
    URZĄD_SKARBOWY_WARSZAWA_PRAGA = "URZĄD_SKARBOWY_WARSZAWA_PRAGA"
    PIERWSZY_URZĄD_SKARBOWY_WARSZAWA_ŚRÓDMIEŚCIE = "PIERWSZY_URZĄD_SKARBOWY_WARSZAWA_ŚRÓDMIEŚCIE"
    DRUGI_URZĄD_SKARBOWY_WARSZAWA_ŚRÓDMIEŚCIE = "DRUGI_URZĄD_SKARBOWY_WARSZAWA_ŚRÓDMIEŚCIE"
    URZĄD_SKARBOWY_WARSZAWA_TARGÓWEK = "URZĄD_SKARBOWY_WARSZAWA_TARGÓWEK"
    URZĄD_SKARBOWY_WARSZAWA_URSYNÓW = "URZĄD_SKARBOWY_WARSZAWA_URSYNÓW"
    URZĄD_SKARBOWY_WARSZAWA_WAWER = "URZĄD_SKARBOWY_WARSZAWA_WAWER"
    URZĄD_SKARBOWY_WARSZAWA_WOLA = "URZĄD_SKARBOWY_WARSZAWA_WOLA"
    URZĄD_SKARBOWY_W_WĘGROWIE = "URZĄD_SKARBOWY_W_WĘGROWIE"
    URZĄD_SKARBOWY_W_WOŁOMINIE = "URZĄD_SKARBOWY_W_WOŁOMINIE"
    URZĄD_SKARBOWY_W_WYSZKOWIE = "URZĄD_SKARBOWY_W_WYSZKOWIE"
    URZĄD_SKARBOWY_W_ZWOLENIU = "URZĄD_SKARBOWY_W_ZWOLENIU"
    URZĄD_SKARBOWY_W_ŻUROMINIE = "URZĄD_SKARBOWY_W_ŻUROMINIE"
    URZĄD_SKARBOWY_W_ŻYRARDOWIE = "URZĄD_SKARBOWY_W_ŻYRARDOWIE"
    URZĄD_SKARBOWY_W_LIPSKU = "URZĄD_SKARBOWY_W_LIPSKU"
    URZĄD_SKARBOWY_W_PRZYSUSZE = "URZĄD_SKARBOWY_W_PRZYSUSZE"
    TRZECI_URZĄD_SKARBOWY_WARSZAWA_ŚRÓDMIEŚCIE = "TRZECI_URZĄD_SKARBOWY_WARSZAWA_ŚRÓDMIEŚCIE"
    PIERWSZY_MAZOWIECKI_URZĄD_SKARBOWY_W_WARSZAWIE = "PIERWSZY_MAZOWIECKI_URZĄD_SKARBOWY_W_WARSZAWIE"
    DRUGI_MAZOWIECKI_URZĄD_SKARBOWY_W_WARSZAWIE = "DRUGI_MAZOWIECKI_URZĄD_SKARBOWY_W_WARSZAWIE"
    TRZECI_MAZOWIECKI_URZĄD_SKARBOWY_W_RADOMIU = "TRZECI_MAZOWIECKI_URZĄD_SKARBOWY_W_RADOMIU"
    URZĄD_SKARBOWY_W_BRZEGU = "URZĄD_SKARBOWY_W_BRZEGU"
    URZĄD_SKARBOWY_W_GŁUBCZYCACH = "URZĄD_SKARBOWY_W_GŁUBCZYCACH"
    URZĄD_SKARBOWY_W_KĘDZIERZYNIE_KOŹLU = "URZĄD_SKARBOWY_W_KĘDZIERZYNIE_KOŹLU"
    URZĄD_SKARBOWY_W_KLUCZBORKU = "URZĄD_SKARBOWY_W_KLUCZBORKU"
    URZĄD_SKARBOWY_W_NAMYSŁOWIE = "URZĄD_SKARBOWY_W_NAMYSŁOWIE"
    URZĄD_SKARBOWY_W_NYSIE = "URZĄD_SKARBOWY_W_NYSIE"
    URZĄD_SKARBOWY_W_OLEŚNIE = "URZĄD_SKARBOWY_W_OLEŚNIE"
    PIERWSZY_URZĄD_SKARBOWY_W_OPOLU = "PIERWSZY_URZĄD_SKARBOWY_W_OPOLU"
    DRUGI_URZĄD_SKARBOWY_W_OPOLU = "DRUGI_URZĄD_SKARBOWY_W_OPOLU"
    URZĄD_SKARBOWY_W_PRUDNIKU = "URZĄD_SKARBOWY_W_PRUDNIKU"
    URZĄD_SKARBOWY_W_STRZELCACH_OPOLSKICH = "URZĄD_SKARBOWY_W_STRZELCACH_OPOLSKICH"
    URZĄD_SKARBOWY_W_KRAPKOWICACH = "URZĄD_SKARBOWY_W_KRAPKOWICACH"
    OPOLSKI_URZĄD_SKARBOWY_W_OPOLU = "OPOLSKI_URZĄD_SKARBOWY_W_OPOLU"
    URZĄD_SKARBOWY_W_BRZOZOWIE = "URZĄD_SKARBOWY_W_BRZOZOWIE"
    URZĄD_SKARBOWY_W_DĘBICY = "URZĄD_SKARBOWY_W_DĘBICY"
    URZĄD_SKARBOWY_W_JAROSŁAWIU = "URZĄD_SKARBOWY_W_JAROSŁAWIU"
    URZĄD_SKARBOWY_W_JAŚLE = "URZĄD_SKARBOWY_W_JAŚLE"
    URZĄD_SKARBOWY_W_KOLBUSZOWEJ = "URZĄD_SKARBOWY_W_KOLBUSZOWEJ"
    URZĄD_SKARBOWY_W_KROŚNIE = "URZĄD_SKARBOWY_W_KROŚNIE"
    URZĄD_SKARBOWY_W_LESKU = "URZĄD_SKARBOWY_W_LESKU"
    URZĄD_SKARBOWY_W_LEŻAJSKU = "URZĄD_SKARBOWY_W_LEŻAJSKU"
    URZĄD_SKARBOWY_W_LUBACZOWIE = "URZĄD_SKARBOWY_W_LUBACZOWIE"
    URZĄD_SKARBOWY_W_ŁAŃCUCIE = "URZĄD_SKARBOWY_W_ŁAŃCUCIE"
    URZĄD_SKARBOWY_W_MIELCU = "URZĄD_SKARBOWY_W_MIELCU"
    URZĄD_SKARBOWY_W_PRZEMYŚLU = "URZĄD_SKARBOWY_W_PRZEMYŚLU"
    URZĄD_SKARBOWY_W_PRZEWORSKU = "URZĄD_SKARBOWY_W_PRZEWORSKU"
    URZĄD_SKARBOWY_W_ROPCZYCACH = "URZĄD_SKARBOWY_W_ROPCZYCACH"
    PIERWSZY_URZĄD_SKARBOWY_W_RZESZOWIE = "PIERWSZY_URZĄD_SKARBOWY_W_RZESZOWIE"
    URZĄD_SKARBOWY_W_SANOKU = "URZĄD_SKARBOWY_W_SANOKU"
    URZĄD_SKARBOWY_W_STALOWEJ_WOLI = "URZĄD_SKARBOWY_W_STALOWEJ_WOLI"
    URZĄD_SKARBOWY_W_STRZYŻOWIE = "URZĄD_SKARBOWY_W_STRZYŻOWIE"
    URZĄD_SKARBOWY_W_TARNOBRZEGU = "URZĄD_SKARBOWY_W_TARNOBRZEGU"
    URZĄD_SKARBOWY_W_USTRZYKACH_DOLNYCH = "URZĄD_SKARBOWY_W_USTRZYKACH_DOLNYCH"
    DRUGI_URZĄD_SKARBOWY_W_RZESZOWIE = "DRUGI_URZĄD_SKARBOWY_W_RZESZOWIE"
    URZĄD_SKARBOWY_W_NISKU = "URZĄD_SKARBOWY_W_NISKU"
    PODKARPACKI_URZĄD_SKARBOWY_W_RZESZOWIE = "PODKARPACKI_URZĄD_SKARBOWY_W_RZESZOWIE"
    URZĄD_SKARBOWY_W_AUGUSTOWIE = "URZĄD_SKARBOWY_W_AUGUSTOWIE"
    PIERWSZY_URZĄD_SKARBOWY_W_BIAŁYMSTOKU = "PIERWSZY_URZĄD_SKARBOWY_W_BIAŁYMSTOKU"
    DRUGI_URZĄD_SKARBOWY_W_BIAŁYMSTOKU = "DRUGI_URZĄD_SKARBOWY_W_BIAŁYMSTOKU"
    URZĄD_SKARBOWY_W_BIELSKU_PODLASKIM = "URZĄD_SKARBOWY_W_BIELSKU_PODLASKIM"
    URZĄD_SKARBOWY_W_GRAJEWIE = "URZĄD_SKARBOWY_W_GRAJEWIE"
    URZĄD_SKARBOWY_W_KOLNIE = "URZĄD_SKARBOWY_W_KOLNIE"
    URZĄD_SKARBOWY_W_ŁOMŻY = "URZĄD_SKARBOWY_W_ŁOMŻY"
    URZĄD_SKARBOWY_W_MOŃKACH = "URZĄD_SKARBOWY_W_MOŃKACH"
    URZĄD_SKARBOWY_W_SIEMIATYCZACH = "URZĄD_SKARBOWY_W_SIEMIATYCZACH"
    URZĄD_SKARBOWY_W_SOKÓŁCE = "URZĄD_SKARBOWY_W_SOKÓŁCE"
    URZĄD_SKARBOWY_W_SUWAŁKACH = "URZĄD_SKARBOWY_W_SUWAŁKACH"
    URZĄD_SKARBOWY_W_WYSOKIEM_MAZOWIECKIEM = "URZĄD_SKARBOWY_W_WYSOKIEM_MAZOWIECKIEM"
    URZĄD_SKARBOWY_W_ZAMBROWIE = "URZĄD_SKARBOWY_W_ZAMBROWIE"
    URZĄD_SKARBOWY_W_HAJNÓWCE = "URZĄD_SKARBOWY_W_HAJNÓWCE"
    PODLASKI_URZĄD_SKARBOWY_W_BIAŁYMSTOKU = "PODLASKI_URZĄD_SKARBOWY_W_BIAŁYMSTOKU"
    URZĄD_SKARBOWY_W_BYTOWIE = "URZĄD_SKARBOWY_W_BYTOWIE"
    URZĄD_SKARBOWY_W_CHOJNICACH = "URZĄD_SKARBOWY_W_CHOJNICACH"
    URZĄD_SKARBOWY_W_CZŁUCHOWIE = "URZĄD_SKARBOWY_W_CZŁUCHOWIE"
    PIERWSZY_URZĄD_SKARBOWY_W_GDAŃSKU = "PIERWSZY_URZĄD_SKARBOWY_W_GDAŃSKU"
    DRUGI_URZĄD_SKARBOWY_W_GDAŃSKU = "DRUGI_URZĄD_SKARBOWY_W_GDAŃSKU"
    TRZECI_URZĄD_SKARBOWY_W_GDAŃSKU = "TRZECI_URZĄD_SKARBOWY_W_GDAŃSKU"
    PIERWSZY_URZĄD_SKARBOWY_W_GDYNI = "PIERWSZY_URZĄD_SKARBOWY_W_GDYNI"
    DRUGI_URZĄD_SKARBOWY_W_GDYNI = "DRUGI_URZĄD_SKARBOWY_W_GDYNI"
    URZĄD_SKARBOWY_W_KARTUZACH = "URZĄD_SKARBOWY_W_KARTUZACH"
    URZĄD_SKARBOWY_W_KOŚCIERZYNIE = "URZĄD_SKARBOWY_W_KOŚCIERZYNIE"
    URZĄD_SKARBOWY_W_KWIDZYNIE = "URZĄD_SKARBOWY_W_KWIDZYNIE"
    URZĄD_SKARBOWY_W_LĘBORKU = "URZĄD_SKARBOWY_W_LĘBORKU"
    URZĄD_SKARBOWY_W_MALBORKU = "URZĄD_SKARBOWY_W_MALBORKU"
    URZĄD_SKARBOWY_W_PUCKU = "URZĄD_SKARBOWY_W_PUCKU"
    URZĄD_SKARBOWY_W_SŁUPSKU = "URZĄD_SKARBOWY_W_SŁUPSKU"
    URZĄD_SKARBOWY_W_SOPOCIE = "URZĄD_SKARBOWY_W_SOPOCIE"
    URZĄD_SKARBOWY_W_STAROGARDZIE_GDAŃSKIM = "URZĄD_SKARBOWY_W_STAROGARDZIE_GDAŃSKIM"
    URZĄD_SKARBOWY_W_TCZEWIE = "URZĄD_SKARBOWY_W_TCZEWIE"
    URZĄD_SKARBOWY_W_WEJHEROWIE = "URZĄD_SKARBOWY_W_WEJHEROWIE"
    URZĄD_SKARBOWY_W_PRUSZCZU_GDAŃSKIM = "URZĄD_SKARBOWY_W_PRUSZCZU_GDAŃSKIM"
    POMORSKI_URZĄD_SKARBOWY_W_GDAŃSKU = "POMORSKI_URZĄD_SKARBOWY_W_GDAŃSKU"
    URZĄD_SKARBOWY_W_BĘDZINIE = "URZĄD_SKARBOWY_W_BĘDZINIE"
    PIERWSZY_URZĄD_SKARBOWY_W_BIELSKU_BIAŁEJ = "PIERWSZY_URZĄD_SKARBOWY_W_BIELSKU_BIAŁEJ"
    DRUGI_URZĄD_SKARBOWY_W_BIELSKU_BIAŁEJ = "DRUGI_URZĄD_SKARBOWY_W_BIELSKU_BIAŁEJ"
    URZĄD_SKARBOWY_W_BYTOMIU = "URZĄD_SKARBOWY_W_BYTOMIU"
    URZĄD_SKARBOWY_W_CHORZOWIE = "URZĄD_SKARBOWY_W_CHORZOWIE"
    URZĄD_SKARBOWY_W_CIESZYNIE = "URZĄD_SKARBOWY_W_CIESZYNIE"
    URZĄD_SKARBOWY_W_CZECHOWICACH_DZIEDZICACH = "URZĄD_SKARBOWY_W_CZECHOWICACH_DZIEDZICACH"
    PIERWSZY_URZĄD_SKARBOWY_W_CZĘSTOCHOWIE = "PIERWSZY_URZĄD_SKARBOWY_W_CZĘSTOCHOWIE"
    DRUGI_URZĄD_SKARBOWY_W_CZĘSTOCHOWIE = "DRUGI_URZĄD_SKARBOWY_W_CZĘSTOCHOWIE"
    URZĄD_SKARBOWY_W_DĄBROWIE_GÓRNICZEJ = "URZĄD_SKARBOWY_W_DĄBROWIE_GÓRNICZEJ"
    PIERWSZY_URZĄD_SKARBOWY_W_GLIWICACH = "PIERWSZY_URZĄD_SKARBOWY_W_GLIWICACH"
    DRUGI_URZĄD_SKARBOWY_W_GLIWICACH = "DRUGI_URZĄD_SKARBOWY_W_GLIWICACH"
    URZĄD_SKARBOWY_W_JASTRZĘBIU_ZDROJU = "URZĄD_SKARBOWY_W_JASTRZĘBIU_ZDROJU"
    URZĄD_SKARBOWY_W_JAWORZNIE = "URZĄD_SKARBOWY_W_JAWORZNIE"
    PIERWSZY_URZĄD_SKARBOWY_W_KATOWICACH = "PIERWSZY_URZĄD_SKARBOWY_W_KATOWICACH"
    DRUGI_URZĄD_SKARBOWY_W_KATOWICACH = "DRUGI_URZĄD_SKARBOWY_W_KATOWICACH"
    URZĄD_SKARBOWY_W_KŁOBUCKU = "URZĄD_SKARBOWY_W_KŁOBUCKU"
    URZĄD_SKARBOWY_W_LUBLIŃCU = "URZĄD_SKARBOWY_W_LUBLIŃCU"
    URZĄD_SKARBOWY_W_MIKOŁOWIE = "URZĄD_SKARBOWY_W_MIKOŁOWIE"
    URZĄD_SKARBOWY_W_MYSŁOWICACH = "URZĄD_SKARBOWY_W_MYSŁOWICACH"
    URZĄD_SKARBOWY_W_MYSZKOWIE = "URZĄD_SKARBOWY_W_MYSZKOWIE"
    URZĄD_SKARBOWY_W_PIEKARACH_ŚLĄSKICH = "URZĄD_SKARBOWY_W_PIEKARACH_ŚLĄSKICH"
    URZĄD_SKARBOWY_W_PSZCZYNIE = "URZĄD_SKARBOWY_W_PSZCZYNIE"
    URZĄD_SKARBOWY_W_RACIBORZU = "URZĄD_SKARBOWY_W_RACIBORZU"
    URZĄD_SKARBOWY_W_RUDZIE_ŚLĄSKIEJ = "URZĄD_SKARBOWY_W_RUDZIE_ŚLĄSKIEJ"
    URZĄD_SKARBOWY_W_RYBNIKU = "URZĄD_SKARBOWY_W_RYBNIKU"
    URZĄD_SKARBOWY_W_SIEMIANOWICACH_ŚLĄSKICH = "URZĄD_SKARBOWY_W_SIEMIANOWICACH_ŚLĄSKICH"
    URZĄD_SKARBOWY_W_SOSNOWCU = "URZĄD_SKARBOWY_W_SOSNOWCU"
    URZĄD_SKARBOWY_W_TARNOWSKICH_GÓRACH = "URZĄD_SKARBOWY_W_TARNOWSKICH_GÓRACH"
    URZĄD_SKARBOWY_W_TYCHACH = "URZĄD_SKARBOWY_W_TYCHACH"
    URZĄD_SKARBOWY_W_WODZISŁAWIU_ŚLĄSKIM = "URZĄD_SKARBOWY_W_WODZISŁAWIU_ŚLĄSKIM"
    URZĄD_SKARBOWY_W_ZABRZU = "URZĄD_SKARBOWY_W_ZABRZU"
    URZĄD_SKARBOWY_W_ZAWIERCIU = "URZĄD_SKARBOWY_W_ZAWIERCIU"
    URZĄD_SKARBOWY_W_ŻORACH = "URZĄD_SKARBOWY_W_ŻORACH"
    URZĄD_SKARBOWY_W_ŻYWCU = "URZĄD_SKARBOWY_W_ŻYWCU"
    PIERWSZY_ŚLĄSKI_URZĄD_SKARBOWY_W_SOSNOWCU = "PIERWSZY_ŚLĄSKI_URZĄD_SKARBOWY_W_SOSNOWCU"
    DRUGI_ŚLĄSKI_URZĄD_SKARBOWY_W_BIELSKU_BIAŁEJ = "DRUGI_ŚLĄSKI_URZĄD_SKARBOWY_W_BIELSKU_BIAŁEJ"
    URZĄD_SKARBOWY_W_BUSKU_ZDROJU = "URZĄD_SKARBOWY_W_BUSKU_ZDROJU"
    URZĄD_SKARBOWY_W_JĘDRZEJOWIE = "URZĄD_SKARBOWY_W_JĘDRZEJOWIE"
    PIERWSZY_URZĄD_SKARBOWY_W_KIELCACH = "PIERWSZY_URZĄD_SKARBOWY_W_KIELCACH"
    DRUGI_URZĄD_SKARBOWY_W_KIELCACH = "DRUGI_URZĄD_SKARBOWY_W_KIELCACH"
    URZĄD_SKARBOWY_W_KOŃSKICH = "URZĄD_SKARBOWY_W_KOŃSKICH"
    URZĄD_SKARBOWY_W_OPATOWIE = "URZĄD_SKARBOWY_W_OPATOWIE"
    URZĄD_SKARBOWY_W_OSTROWCU_ŚWIĘTOKRZYSKIM = "URZĄD_SKARBOWY_W_OSTROWCU_ŚWIĘTOKRZYSKIM"
    URZĄD_SKARBOWY_W_PIŃCZOWIE = "URZĄD_SKARBOWY_W_PIŃCZOWIE"
    URZĄD_SKARBOWY_W_SANDOMIERZU = "URZĄD_SKARBOWY_W_SANDOMIERZU"
    URZĄD_SKARBOWY_W_SKARŻYSKU_KAMIENNEJ = "URZĄD_SKARBOWY_W_SKARŻYSKU_KAMIENNEJ"
    URZĄD_SKARBOWY_W_STARACHOWICACH = "URZĄD_SKARBOWY_W_STARACHOWICACH"
    URZĄD_SKARBOWY_W_STASZOWIE = "URZĄD_SKARBOWY_W_STASZOWIE"
    URZĄD_SKARBOWY_W_KAZIMIERZY_WIELKIEJ = "URZĄD_SKARBOWY_W_KAZIMIERZY_WIELKIEJ"
    URZĄD_SKARBOWY_WE_WŁOSZCZOWIE = "URZĄD_SKARBOWY_WE_WŁOSZCZOWIE"
    ŚWIĘTOKRZYSKI_URZĄD_SKARBOWY_W_KIELCACH = "ŚWIĘTOKRZYSKI_URZĄD_SKARBOWY_W_KIELCACH"
    URZĄD_SKARBOWY_W_BARTOSZYCACH = "URZĄD_SKARBOWY_W_BARTOSZYCACH"
    URZĄD_SKARBOWY_W_BRANIEWIE = "URZĄD_SKARBOWY_W_BRANIEWIE"
    URZĄD_SKARBOWY_W_DZIAŁDOWIE = "URZĄD_SKARBOWY_W_DZIAŁDOWIE"
    URZĄD_SKARBOWY_W_ELBLĄGU = "URZĄD_SKARBOWY_W_ELBLĄGU"
    URZĄD_SKARBOWY_W_EŁKU = "URZĄD_SKARBOWY_W_EŁKU"
    URZĄD_SKARBOWY_W_GIŻYCKU = "URZĄD_SKARBOWY_W_GIŻYCKU"
    URZĄD_SKARBOWY_W_IŁAWIE = "URZĄD_SKARBOWY_W_IŁAWIE"
    URZĄD_SKARBOWY_W_KĘTRZYNIE = "URZĄD_SKARBOWY_W_KĘTRZYNIE"
    URZĄD_SKARBOWY_W_NIDZICY = "URZĄD_SKARBOWY_W_NIDZICY"
    URZĄD_SKARBOWY_W_NOWYM_MIEŚCIE_LUBAWSKIM = "URZĄD_SKARBOWY_W_NOWYM_MIEŚCIE_LUBAWSKIM"
    URZĄD_SKARBOWY_W_OLECKU = "URZĄD_SKARBOWY_W_OLECKU"
    URZĄD_SKARBOWY_W_OLSZTYNIE = "URZĄD_SKARBOWY_W_OLSZTYNIE"
    URZĄD_SKARBOWY_W_OSTRÓDZIE = "URZĄD_SKARBOWY_W_OSTRÓDZIE"
    URZĄD_SKARBOWY_W_PISZU = "URZĄD_SKARBOWY_W_PISZU"
    URZĄD_SKARBOWY_W_SZCZYTNIE = "URZĄD_SKARBOWY_W_SZCZYTNIE"
    WARMIŃSKO_MAZURSKI_URZĄD_SKARBOWY_W_OLSZTYNIE = "WARMIŃSKO_MAZURSKI_URZĄD_SKARBOWY_W_OLSZTYNIE"
    URZĄD_SKARBOWY_W_CZARNKOWIE = "URZĄD_SKARBOWY_W_CZARNKOWIE"
    URZĄD_SKARBOWY_W_GNIEŹNIE = "URZĄD_SKARBOWY_W_GNIEŹNIE"
    URZĄD_SKARBOWY_W_GOSTYNIU = "URZĄD_SKARBOWY_W_GOSTYNIU"
    URZĄD_SKARBOWY_W_GRODZISKU_WIELKOPOLSKIM = "URZĄD_SKARBOWY_W_GRODZISKU_WIELKOPOLSKIM"
    URZĄD_SKARBOWY_W_JAROCINIE = "URZĄD_SKARBOWY_W_JAROCINIE"
    PIERWSZY_URZĄD_SKARBOWY_W_KALISZU = "PIERWSZY_URZĄD_SKARBOWY_W_KALISZU"
    DRUGI_URZĄD_SKARBOWY_W_KALISZU = "DRUGI_URZĄD_SKARBOWY_W_KALISZU"
    URZĄD_SKARBOWY_W_KĘPNIE = "URZĄD_SKARBOWY_W_KĘPNIE"
    URZĄD_SKARBOWY_W_KOLE = "URZĄD_SKARBOWY_W_KOLE"
    URZĄD_SKARBOWY_W_KONINIE = "URZĄD_SKARBOWY_W_KONINIE"
    URZĄD_SKARBOWY_W_KOŚCIANIE = "URZĄD_SKARBOWY_W_KOŚCIANIE"
    URZĄD_SKARBOWY_W_KROTOSZYNIE = "URZĄD_SKARBOWY_W_KROTOSZYNIE"
    URZĄD_SKARBOWY_W_LESZNIE = "URZĄD_SKARBOWY_W_LESZNIE"
    URZĄD_SKARBOWY_W_MIĘDZYCHODZIE = "URZĄD_SKARBOWY_W_MIĘDZYCHODZIE"
    URZĄD_SKARBOWY_W_NOWYM_TOMYŚLU = "URZĄD_SKARBOWY_W_NOWYM_TOMYŚLU"
    URZĄD_SKARBOWY_W_OSTROWIE_WIELKOPOLSKIM = "URZĄD_SKARBOWY_W_OSTROWIE_WIELKOPOLSKIM"
    URZĄD_SKARBOWY_W_OSTRZESZOWIE = "URZĄD_SKARBOWY_W_OSTRZESZOWIE"
    URZĄD_SKARBOWY_W_PILE = "URZĄD_SKARBOWY_W_PILE"
    URZĄD_SKARBOWY_POZNAŃ_GRUNWALD = "URZĄD_SKARBOWY_POZNAŃ_GRUNWALD"
    URZĄD_SKARBOWY_POZNAŃ_JEŻYCE = "URZĄD_SKARBOWY_POZNAŃ_JEŻYCE"
    URZĄD_SKARBOWY_POZNAŃ_NOWE_MIASTO = "URZĄD_SKARBOWY_POZNAŃ_NOWE_MIASTO"
    PIERWSZY_URZĄD_SKARBOWY_W_POZNANIU = "PIERWSZY_URZĄD_SKARBOWY_W_POZNANIU"
    URZĄD_SKARBOWY_POZNAŃ_WINOGRADY = "URZĄD_SKARBOWY_POZNAŃ_WINOGRADY"
    URZĄD_SKARBOWY_POZNAŃ_WILDA = "URZĄD_SKARBOWY_POZNAŃ_WILDA"
    URZĄD_SKARBOWY_W_RAWICZU = "URZĄD_SKARBOWY_W_RAWICZU"
    URZĄD_SKARBOWY_W_SŁUPCY = "URZĄD_SKARBOWY_W_SŁUPCY"
    URZĄD_SKARBOWY_W_SZAMOTUŁACH = "URZĄD_SKARBOWY_W_SZAMOTUŁACH"
    URZĄD_SKARBOWY_W_ŚREMIE = "URZĄD_SKARBOWY_W_ŚREMIE"
    URZĄD_SKARBOWY_W_ŚRODZIE_WIELKOPOLSKIEJ = "URZĄD_SKARBOWY_W_ŚRODZIE_WIELKOPOLSKIEJ"
    URZĄD_SKARBOWY_W_TURKU = "URZĄD_SKARBOWY_W_TURKU"
    URZĄD_SKARBOWY_W_WĄGROWCU = "URZĄD_SKARBOWY_W_WĄGROWCU"
    URZĄD_SKARBOWY_W_WOLSZTYNIE = "URZĄD_SKARBOWY_W_WOLSZTYNIE"
    URZĄD_SKARBOWY_WE_WRZEŚNI = "URZĄD_SKARBOWY_WE_WRZEŚNI"
    URZĄD_SKARBOWY_W_ZŁOTOWIE = "URZĄD_SKARBOWY_W_ZŁOTOWIE"
    URZĄD_SKARBOWY_W_CHODZIEŻY = "URZĄD_SKARBOWY_W_CHODZIEŻY"
    URZĄD_SKARBOWY_W_OBORNIKACH = "URZĄD_SKARBOWY_W_OBORNIKACH"
    URZĄD_SKARBOWY_W_PLESZEWIE = "URZĄD_SKARBOWY_W_PLESZEWIE"
    PIERWSZY_WIELKOPOLSKI_URZĄD_SKARBOWY_W_POZNANIU = "PIERWSZY_WIELKOPOLSKI_URZĄD_SKARBOWY_W_POZNANIU"
    DRUGI_WIELKOPOLSKI_URZĄD_SKARBOWY_W_KALISZU = "DRUGI_WIELKOPOLSKI_URZĄD_SKARBOWY_W_KALISZU"
    URZĄD_SKARBOWY_W_BIAŁOGARDZIE = "URZĄD_SKARBOWY_W_BIAŁOGARDZIE"
    URZĄD_SKARBOWY_W_CHOSZCZNIE = "URZĄD_SKARBOWY_W_CHOSZCZNIE"
    URZĄD_SKARBOWY_W_DRAWSKU_POMORSKIM = "URZĄD_SKARBOWY_W_DRAWSKU_POMORSKIM"
    URZĄD_SKARBOWY_W_GOLENIOWIE = "URZĄD_SKARBOWY_W_GOLENIOWIE"
    URZĄD_SKARBOWY_W_GRYFICACH = "URZĄD_SKARBOWY_W_GRYFICACH"
    URZĄD_SKARBOWY_W_GRYFINIE = "URZĄD_SKARBOWY_W_GRYFINIE"
    URZĄD_SKARBOWY_W_KAMIENIU_POMORSKIM = "URZĄD_SKARBOWY_W_KAMIENIU_POMORSKIM"
    URZĄD_SKARBOWY_W_KOŁOBRZEGU = "URZĄD_SKARBOWY_W_KOŁOBRZEGU"
    PIERWSZY_URZĄD_SKARBOWY_W_KOSZALINIE = "PIERWSZY_URZĄD_SKARBOWY_W_KOSZALINIE"
    DRUGI_URZĄD_SKARBOWY_W_KOSZALINIE = "DRUGI_URZĄD_SKARBOWY_W_KOSZALINIE"
    URZĄD_SKARBOWY_W_MYŚLIBORZU = "URZĄD_SKARBOWY_W_MYŚLIBORZU"
    URZĄD_SKARBOWY_W_PYRZYCACH = "URZĄD_SKARBOWY_W_PYRZYCACH"
    URZĄD_SKARBOWY_W_STARGARDZIE = "URZĄD_SKARBOWY_W_STARGARDZIE"
    PIERWSZY_URZĄD_SKARBOWY_W_SZCZECINIE = "PIERWSZY_URZĄD_SKARBOWY_W_SZCZECINIE"
    DRUGI_URZĄD_SKARBOWY_W_SZCZECINIE = "DRUGI_URZĄD_SKARBOWY_W_SZCZECINIE"
    TRZECI_URZĄD_SKARBOWY_W_SZCZECINIE = "TRZECI_URZĄD_SKARBOWY_W_SZCZECINIE"
    URZĄD_SKARBOWY_W_SZCZECINKU = "URZĄD_SKARBOWY_W_SZCZECINKU"
    URZĄD_SKARBOWY_W_ŚWINOUJŚCIU = "URZĄD_SKARBOWY_W_ŚWINOUJŚCIU"
    URZĄD_SKARBOWY_W_WAŁCZU = "URZĄD_SKARBOWY_W_WAŁCZU"
    ZACHODNIOPOMORSKI_URZĄD_SKARBOWY_W_SZCZECINIE = "ZACHODNIOPOMORSKI_URZĄD_SKARBOWY_W_SZCZECINIE"


class PodmiotSkladajacy(Enum):
    PODMIOT_ZOBOWIAZANY = "PODMIOT_ZOBOWIAZANY"
    STRONA_UMOWY_ZAMIANY = "STRONA_UMOWY_ZAMIANY"
    WSPOLNIK_SPOLKI_CYWILNEJ = "WSPOLNIK_SPOLKI_CYWILNEJ"
    POZYCZKOBIORCA = "POZYCZKOBIORCA"
    INNY_PODMIOT = "INNY_PODMIOT"


class PrzedmiotOpodatkowania(Enum):
    UMOWA = "UMOWA"
    ZMIANA_UMOWY = "ZMIANA_UMOWY"
    ORZECZENIE_SADU_LUB_UGODA = "ORZECZENIE_SADU_LUB_UGODA"
    INNE = "INNE"


class MiejscePolozenia(Enum):
    TERYTORIUM_RP = "TERYTORIUM_RP"
    POZA_TERYTORIUM_RP = "POZA_TERYTORIUM_RP"


class TypSpolki(Enum):
    OSOBOWA = "OSOBOWA"
    KAPITALOWA = "KAPITALOWA"


class PodstawaOpodatkowania(Enum):
    ZAWARCIE_UMOWY_SPOLKI ="ZAWARCIE_UMOWY_SPOLKI"
    ZWIEKSZENIE_MAJATKU_SPOLKI ="ZWIEKSZENIE_MAJATKU_SPOLKI"
    DOPLATA ="DOPLATA"
    POZYCZKA_UDZIELONA_SPOLCE ="POZYCZKA_UDZIELONA_SPOLCE"
    ODDANIE_RZECZY_DO_UZYWANIA ="ODDANIE_RZECZY_DO_UZYWANIA"
    PRZEKSZTALCENIE_SPOLEK ="PRZEKSZTALCENIE_SPOLEK"
    LACZENIE_SPOLEK ="LACZENIE_SPOLEK"
    PRZENIESIENIE_SIEDZIBY ="PRZENIESIENIE_SIEDZIBY"


class PartialSectionA(ErrorSuppressingModel):
    """Sekcja A: Nagłówek deklaracji"""
    kod_formularza: Optional[Literal["PCC-3"]] = "PCC-3"
    wariant_formularza: Optional[Literal[6]] = 6
    cel_zlozenia: Optional[Annotated[CelZlozenia, form_field("P_6")]] = None
    data_dokonania_czynnosci: Optional[Annotated[date, form_field("P_4")]] = None
    nazwa_urzedu: Optional[Annotated[TaxOffice, form_field("P_5")]] = None
    is_complete: Optional[bool]

    @validator('data_dokonania_czynnosci')
    def validate_date(cls, v):
        if v and v < date(2024, 1, 1):
            raise ValueError('Data musi być nie wcześniejsza niż 1 stycznia 2024')
        return v


class PartialAdres(ErrorSuppressingModel):
    kod_kraju: Optional[Annotated[str, form_field("P_8")]] = None
    wojewodztwo: Optional[Annotated[Optional[Voivodeship], form_field("P_9")]] = Field(None, min_length=1,
                                                                                       max_length=36)
    powiat: Optional[Annotated[Optional[County], form_field("P_10")]] = Field(None, min_length=1, max_length=36)
    gmina: Optional[Annotated[Optional[Municipality], form_field("P_11")]] = Field(None, min_length=1, max_length=36)
    ulica: Optional[Annotated[Optional[str], form_field("P_12")]] = Field(None, min_length=1, max_length=65)
    nr_domu: Optional[Annotated[str, form_field("P_13")]] = Field(None, min_length=1, max_length=9)
    nr_lokalu: Optional[Annotated[Optional[str], form_field("P_14")]] = Field(None, min_length=1, max_length=10)
    miejscowosc: Optional[Annotated[str, form_field("P_15")]] = Field(None, min_length=1, max_length=56)
    kod_pocztowy: Optional[Annotated[Optional[str], form_field("P_16")]] = None

    @validator('kod_pocztowy')
    def validate_kod_pocztowy(cls, v):
        if v is not None and not re.match(r'^\d{2}-\d{3}$', v):
            raise ValueError('Nieprawidłowy format kodu pocztowego')
        return v


class PartialOsobaFizyczna(ErrorSuppressingModel):
    nip: Optional[Annotated[Optional[str], form_field("P_17")]] = None
    pesel: Optional[Annotated[Optional[str], form_field("P_18")]] = None
    imie_pierwsze: Optional[Annotated[str, form_field("P_19")]] = Field(None, min_length=1, max_length=30)
    nazwisko: Optional[Annotated[str, form_field("P_20")]] = Field(None, min_length=1, max_length=81)
    data_urodzenia: Optional[Annotated[date, form_field("P_21")]] = None
    imie_ojca: Optional[Annotated[Optional[str], form_field("P_22")]] = Field(None, min_length=1, max_length=30)
    imie_matki: Optional[Annotated[Optional[str], form_field("P_23")]] = Field(None, min_length=1, max_length=30)

    @validator('nip')
    def validate_nip(cls, v):
        if v is not None and not re.match(r'^\d{10}$', v):
            raise ValueError('Nieprawidłowy format NIP')
        return v

    @validator('pesel')
    def validate_pesel(cls, v):
        if v is not None and not re.match(r'^\d{11}$', v):
            raise ValueError('Nieprawidłowy format PESEL')
        return v


class PartialOsobaNiefizyczna(ErrorSuppressingModel):
    nip: Optional[Annotated[str, form_field("P_24")]] = None
    pelna_nazwa: Optional[Annotated[str, form_field("P_25")]] = Field(None, min_length=1, max_length=240)
    skrocona_nazwa: Optional[Annotated[str, form_field("P_26")]] = Field(None, min_length=1, max_length=70)

    @validator('nip')
    def validate_nip(cls, v):
        if v is not None and not re.match(r'^\d{10}$', v):
            raise ValueError('Nieprawidłowy format NIP')
        return v


class PartialSectionB(ErrorSuppressingModel):
    """Sekcja B: Dane podatnika"""
    osoba_fizyczna: Optional[PartialOsobaFizyczna] = None
    osoba_niefizyczna: Optional[PartialOsobaNiefizyczna] = None
    adres_zamieszkania_siedziby: Optional[PartialAdres] = None
    podmiot_skladajacy: Optional[Annotated[PodmiotSkladajacy, form_field("P_7")]] = None
    is_complete: Optional[bool]


class PartialSectionC(ErrorSuppressingModel):
    """Sekcja C: Przedmiot opodatkowania i treść czynności cywilnoprawnej"""
    przedmiot_opodatkowania: Optional[Annotated[PrzedmiotOpodatkowania, form_field("P_20")]] = None
    miejsce_polozenia: Optional[Annotated[Optional[MiejscePolozenia], form_field("P_21")]] = None
    miejsce_dokonania_czynnosci: Optional[Annotated[Optional[MiejscePolozenia], form_field("P_22")]] = None
    tresc_czynnosci: Optional[Annotated[constr(max_length=2000), form_field("P_23")]] = None
    is_complete: Optional[bool]


class PartialSectionD(ErrorSuppressingModel):
    """Sekcja D: Obliczenie należnego podatku od czynności cywilnoprawnych, z wyjątkiem umowy spółki lub jej zmiany"""
    podstawa_opodatkowania: Optional[Annotated[Optional[int], form_field("P_26")]] = Field(None, ge=0)
    kwota_podatku: Optional[Annotated[Optional[int], form_field("P_27")]] = Field(None, ge=0)
    kwota_podatku_naleznego: Optional[Annotated[Optional[int], form_field("P_46")]] = Field(None, ge=0)
    is_complete: Optional[bool]


class PartialSectionE(ErrorSuppressingModel):
    """Sekcja E: Obliczenie należnego podatku od umowy spółki / zmiany umowy spółki"""
    typ_spolki: Optional[Annotated[Optional[TypSpolki], form_field("P_47")]] = None
    podstawa_opodatkowania: Optional[Annotated[Optional[PodstawaOpodatkowania], form_field("P_48")]] = None
    kwota_podstawy_opodatkowania: Optional[Annotated[Optional[int], form_field("P_49")]] = Field(None, ge=0)
    koszty: Optional[Annotated[Optional[float], form_field("P_50")]] = Field(None, ge=0)
    podstawa_obliczenia_podatku: Optional[Annotated[Optional[float], form_field("P_51")]] = Field(None, ge=0)
    kwota_podatku: Optional[Annotated[Optional[int], form_field("P_52")]] = Field(None, ge=0)
    is_complete: Optional[bool]


class PartialSectionF(ErrorSuppressingModel):
    """Sekcja F: Podatek do zapłaty"""
    kwota_podatku_do_zaplaty: Optional[Annotated[int, form_field("P_53")]] = Field(None, ge=0)
    is_complete: Optional[bool]


class PartialSectionG(ErrorSuppressingModel):
    """Sekcja G: Informacje dodatkowe"""
    wojewodztwo: Optional[Annotated[Optional[str], form_field("P_54")]] = Field(None, min_length=1, max_length=36)
    powiat: Optional[Annotated[Optional[str], form_field("P_55")]] = Field(None, min_length=1, max_length=36)
    gmina: Optional[Annotated[Optional[str], form_field("P_56")]] = Field(None, min_length=1, max_length=36)
    ulica: Optional[Annotated[Optional[str], form_field("P_57")]] = Field(None, min_length=1, max_length=65)
    nr_domu: Optional[Annotated[Optional[str], form_field("P_58")]] = Field(None, min_length=1, max_length=9)
    nr_lokalu: Optional[Annotated[Optional[str], form_field("P_59")]] = Field(None, min_length=1, max_length=10)
    miejscowosc: Optional[Annotated[Optional[str], form_field("P_60")]] = Field(None, min_length=1, max_length=56)
    kod_pocztowy: Optional[Annotated[Optional[str], form_field("P_61")]] = None
    is_complete: Optional[bool]

    @validator('kod_pocztowy')
    def validate_kod_pocztowy(cls, v):
        if v is not None and not re.match(r'^\d{2}-\d{3}$', v):
            raise ValueError('Nieprawidłowy format kodu pocztowego')
        return v


class PartialSectionH(ErrorSuppressingModel):
    """Sekcja H: Informacja o załącznikach"""
    liczba_zalacznikow: Optional[Annotated[Optional[int], form_field("P_62")]] = Field(None, ge=0)
    is_complete: Optional[bool]


class PartialDeklaracja(ErrorSuppressingModel):
    sekcja_a: Optional[PartialSectionA] = None
    sekcja_b: Optional[PartialSectionB] = None
    sekcja_c: Optional[PartialSectionC] = None
    sekcja_d: Optional[PartialSectionD] = None
    sekcja_e: Optional[PartialSectionE] = None
    sekcja_f: Optional[PartialSectionF] = None
    sekcja_g: Optional[PartialSectionG] = None
    sekcja_h: Optional[PartialSectionH] = None
    pouczenia: Optional[int] = None
