from tax_assistant.pkg_2022.pkg_09.pkg_13.e_d.definicje_typy.struktury_danych_v12_0_e import (
    TcelZlozenia,
    TidentyfikatorOsobyFizycznej,
    TidentyfikatorOsobyFizycznej1,
    TidentyfikatorOsobyFizycznej2,
    TidentyfikatorOsobyFizycznejPelny,
    TidentyfikatorOsobyFizycznejZagranicznej,
    TidentyfikatorOsobyNiefizycznej,
    TidentyfikatorOsobyNiefizycznej1,
    TidentyfikatorOsobyNiefizycznejPelny,
    TidentyfikatorOsobyNiefizycznejZagranicznej,
    TpodmiotDowolnyBezAdresu,
    TpodmiotDowolnyBezAdresu1,
    TpodmiotDowolnyBezAdresu2,
    TpodmiotDowolnyBezAdresu3,
    Twybor12,
)

__all__ = [
    "TcelZlozenia",
    "TidentyfikatorOsobyFizycznej",
    "TidentyfikatorOsobyFizycznej1",
    "TidentyfikatorOsobyFizycznej2",
    "TidentyfikatorOsobyFizycznejPelny",
    "TidentyfikatorOsobyFizycznejZagranicznej",
    "TidentyfikatorOsobyNiefizycznej",
    "TidentyfikatorOsobyNiefizycznej1",
    "TidentyfikatorOsobyNiefizycznejPelny",
    "TidentyfikatorOsobyNiefizycznejZagranicznej",
    "TpodmiotDowolnyBezAdresu",
    "TpodmiotDowolnyBezAdresu1",
    "TpodmiotDowolnyBezAdresu2",
    "TpodmiotDowolnyBezAdresu3",
    "Twybor12",
]
