from tax_assistant.schemat import (
    Deklaracja,
    PozycjeSzczegoloweP7,
    PozycjeSzczegoloweP20,
    PozycjeSzczegoloweP42,
    PozycjeSzczegoloweP48,
    Tadres,
    TadresPolski,
    TadresPolskiKodKraju,
    TadresZagraniczny,
    TidentyfikatorOsobyFizycznej,
    TidentyfikatorOsobyNiefizycznej,
    TkodFormularza,
    Tnaglowek,
    TnaglowekWariantFormularza,
)

__all__ = [
    "Deklaracja",
    "PozycjeSzczegoloweP20",
    "PozycjeSzczegoloweP42",
    "PozycjeSzczegoloweP48",
    "PozycjeSzczegoloweP7",
    "Tadres",
    "TadresPolski",
    "TadresPolskiKodKraju",
    "TadresZagraniczny",
    "TidentyfikatorOsobyFizycznej",
    "TidentyfikatorOsobyNiefizycznej",
    "TkodFormularza",
    "Tnaglowek",
    "TnaglowekWariantFormularza",
]
